"""support_bundles table for doctor bundle uploads (P2-7)

Revision ID: 0006
Revises: 0005
Create Date: 2026-04-11 16:00:00+00:00

The customer-facing agent ships a ``proxialpha doctor`` command that
builds a redacted ``.tar.gz`` support bundle. Until P2-7 there was
nowhere for the customer to send the bundle — they had to email it,
which slows the support loop and silently drops bundles >10 MB on
several mail providers.

This migration adds the storage layer for the new
``POST /api/support/bundles`` endpoint:

* ``support_bundles`` — one row per uploaded bundle, holding the
  metadata + storage location. The bundle bytes themselves are NOT
  stored in Postgres; the row points at object storage by URI. We
  keep the bytes out of the DB because they are large, opaque, and
  not queryable, and because compliance retention rules differ
  between metadata (kept indefinitely for support history) and the
  bundle blob (kept 90 days then auto-purged by the bucket lifecycle
  rule).

Schema decisions
----------------

* ``id`` is a UUID assigned by the API, NOT generated by Postgres.
  This lets the API write the storage URI in the same transaction as
  the row insert (the URI embeds the id).

* ``org_id`` is RLS-protected via the standard ``tenant_isolation``
  policy — bundles are tenant-scoped and a support engineer reading
  them via the dashboard must come in with the right org context.

* ``size_bytes`` is denormalised (not derived from the blob at read
  time) so the dashboard can render upload sizes without an object-
  storage round trip.

* ``sha256_hex`` is the digest of the original bundle bytes BEFORE
  any server-side encryption is applied. Used to detect bit-rot and
  to deduplicate accidental double-uploads from a panicked operator.

* ``status`` enum is restricted via CHECK to keep the value-space
  small and explicit. ``received`` is the initial state, ``analyzed``
  is set by the support tooling, ``purged`` is set by the cleanup
  job once object storage drops the blob.

* No FK on ``user_id`` because the uploader may be an unauthed
  install-token holder (the agent can call this endpoint mid-enroll
  before a Clerk user exists for it).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create ``support_bundles`` and its tenant_isolation policy."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS support_bundles (
            id              uuid PRIMARY KEY,
            org_id          uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
            agent_id        uuid REFERENCES agents(id) ON DELETE SET NULL,
            uploaded_by     text,
            storage_uri     text NOT NULL,
            size_bytes      bigint NOT NULL,
            sha256_hex      text NOT NULL,
            status          text NOT NULL DEFAULT 'received'
                            CHECK (status IN ('received', 'analyzed', 'purged')),
            uploaded_at     timestamptz NOT NULL DEFAULT now(),
            analyzed_at     timestamptz,
            purged_at       timestamptz,
            notes           text
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_support_bundles_org_uploaded
            ON support_bundles (org_id, uploaded_at DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_support_bundles_status
            ON support_bundles (status, uploaded_at)
            WHERE status != 'purged'
        """
    )
    # Standard tenant isolation. We don't bother with a separate
    # admin policy because the support engineer reads bundles via the
    # bg_worker role which BYPASSRLS.
    op.execute("ALTER TABLE support_bundles ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON support_bundles
            USING (org_id = current_setting('app.current_org_id', true)::uuid)
            WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid)
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON support_bundles")
    op.execute("DROP INDEX IF EXISTS idx_support_bundles_status")
    op.execute("DROP INDEX IF EXISTS idx_support_bundles_org_uploaded")
    op.execute("DROP TABLE IF EXISTS support_bundles")
